### ISSUE TITLE
OwScoreBoardController.exeを実行とありますが...

### ISSUE THREAD

**Issue by johntitor1997** [HIJIKIsw/OwScoreBoard#1]
リポジトリ内にないように思いますが、どこにありますか？

**Comment by HIJIKIsw** [comment]
リポジトリ内にはビルド済みの実行ファイルは含まれませんので、
下記 URL よりビルド済みの実行ファイルが含まれるリリース品をダウンロードしてください。

https://github.com/HIJIKIsw/OwScoreBoard/releases

![ダウンロードリンク](https://user-images.githubusercontent.com/3005814/51074174-18136680-16bf-11e9-8745-8009d3bec217.png)

**Comment by johntitor1997** [comment]
ありがとうございました！

**Comment by HIJIKIsw** [comment]
解決して何よりです。
また何かありましたらご報告ください。
