### ISSUE TITLE
導入方法がわかりません。

### ISSUE THREAD

**Issue by takoyakiow** [HIJIKIsw/OwScoreBoard#2]
始めまして。

HIJIKIsw様のOwScoreBoardを導入したいと考えております。
しかし導入が初めてで導入方法がわかりません。

OwScoreBoard_1.5.9.zip
Source code (zip)
Source code (tar.gz)

以上の三つをDLし解凍できるものはしました。
そのあと、どのファイルに何を入れればよいのかわかりません。OwScoreBoard_1.5.0.zipにあるファイルにexeを移動しで起動し操作してみるとOwScoreBoard.htmlには適応されておらず、その後もいろいろ試行錯誤したのですがうまく動作しません。

よろしければどのように導入すればよいか教えていただいてもよろしいでしょうか？

無知で申し訳ありません。よろしくお願いします。

**Comment by HIJIKIsw** [comment]
takoyakiow さん、初めまして。

OwScoreBoard をご利用いただきありがとうございます。
導入方法が分かりづらく、ご不便をおかけしてしまい申し訳ございません。

導入方法につきましては、過去にも質問があり説明動画を作成した経緯がございます。
不躾ではございますが、よろしければこちらをご覧の上、それでも分からなければ再度ご質問いただきたく存じます。

【OwScoreBoard の使い方】
https://youtu.be/0P4bvq_Gm8U

また、OwScoreBoard と併せてご利用される配信ソフトは、OBS Studio を推奨しております。
上記以外の場合は、動画の手順では設定できなかったり、そもそもご利用いただけない場合もございますので、予めご了承ください。

以上、よろしくお願いいたします。

**Comment by takoyakiow** [comment]
ご返信ありがとうございます。

動画につきましてはありがとうございます。参考にさせていただいたところ導入ができました。

誠にありがとうございます。
